### PR TITLE
Fixed location of include NodeApiVersion.cmake

### PR DESCRIPTION
**Pull request by hikinggrass**
Signed-off-by: Kai-Uwe Hermann <kai-uwe.hermann@pionix.de>

### CODE REVIEW

**Review by a-w50 — CHANGES_REQUESTED** [review]
Couldn't we use CMAKE_MODULE_PATH instead of this unhandy long path?

**Comment by hikinggrass** [comment]
> Couldn't we use CMAKE_MODULE_PATH instead of this unhandy long path?

I think we already set the CMAKE_MODULE_PATH to "${CMAKE_SOURCE_DIR}/cmake" in the root CMakeLists.txt, but this doesn't seem to work

**Comment by a-w50** [comment]
to CMAKE_SOURCE_DIR, here it is PROJECT_SOURCE_DIR

**Review by a-w50 — APPROVED** [review]
I hope it's the right way to choose PROJECT_SOURCE_DIR over CMAKE_SOURCE_DIR, but in case this project gets included via an add_subdirectory, this should be the way to go ...

**Review by corneliusclaussen — APPROVED** [review]

**Pull request merged**
